name: geburtstags_app
description: App für Geburtstagerinnerungen
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.27.3

dependencies:
  avatar_plus: ^0.0.5
  clock: ^1.1.2
  confetti: ^0.8.0
  custom_refresh_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_tilt: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  share_plus: ^10.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
